name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js dependencies
        run: npm install
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: GWJcgw7GHijEqPKDFcUmyIG7
          VERCEL_PROJECT_ID: prj_6WzURHjiDuI2IXfd2z8Zd2lnbBSk
      - name: Check MongoDB connection
        run: npm run check-mongo-connection
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}